[package]
name = "escrow-gateway-primitives"
version = "2.0.0-rc5"
authors = ["Maciej Baj <maciej@maciejbaj.com>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://t3rn.io"
repository = "https://github.com/t3rn/t3rn/"
description = "A crate that hosts a common definitions that are relevant for the escrow-gateway."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# This crate should not rely on any of the frame primitives.
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = [
	"codec/std",
]
